plugins: jekyll-include-cache
theme: minimal
title: Ari Smith
main:
  - title: Contact
    url: /contact/
  - title: Academic
    children:
    - title: Bio
      url: /academic-bio/
    - title: Research Interests
      url: /research-interests/
    - title: Publications
      url: /publications/
    - title: Resume
      url: /docs/resume/
  - title: Music
    children:
    - title: Bio
      url: /music-bio/
    - title: Recordings
      url: /recordings/
    - title: Upcoming Events
      url: /upcoming/
    - title: Catalog of Works
      url: /catalog-of-works/

nav: main
