theme: jekyll-theme-minimal
title: Ari Smith

main:
  - title: Contact
    url: /contact/
  - title: Academic
  - name: Bio
    url: /academic-bio/
  - name: Research Interests
    url: /research-interests/
  - name: Publications
    url: /publications/
  - name: Resume
    url: /docs/resume/
  - title: Music
  - name: Bio
    url: /music-bio/
  - name: Recordings
    url: /recordings/
  - name: Upcoming Events
    url: /upcoming/
  - name: Catalog of Works
    url: /catalog_of_works/
